//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class QueryCalibrationStateResponse : Message
    {
        public const string k_RosMessageName = "control_msgs/QueryCalibrationState";
        public override string RosMessageName => k_RosMessageName;

        public bool is_calibrated;

        public QueryCalibrationStateResponse()
        {
            this.is_calibrated = false;
        }

        public QueryCalibrationStateResponse(bool is_calibrated)
        {
            this.is_calibrated = is_calibrated;
        }

        public static QueryCalibrationStateResponse Deserialize(MessageDeserializer deserializer) => new QueryCalibrationStateResponse(deserializer);

        private QueryCalibrationStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_calibrated);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_calibrated);
        }

        public override string ToString()
        {
            return "QueryCalibrationStateResponse: " +
            "\nis_calibrated: " + is_calibrated.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
