//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class FollowJointTrajectoryResult : Message
    {
        public const string k_RosMessageName = "control_msgs/FollowJointTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public int error_code;
        public const int SUCCESSFUL = 0;
        public const int INVALID_GOAL = -1;
        public const int INVALID_JOINTS = -2;
        public const int OLD_HEADER_TIMESTAMP = -3;
        public const int PATH_TOLERANCE_VIOLATED = -4;
        public const int GOAL_TOLERANCE_VIOLATED = -5;
        //  Human readable description of the error code. Contains complementary
        //  information that is especially useful when execution fails, for instance:
        //  - INVALID_GOAL: The reason for the invalid goal (e.g., the requested
        //    trajectory is in the past).
        //  - INVALID_JOINTS: The mismatch between the expected controller joints
        //    and those provided in the goal.
        //  - PATH_TOLERANCE_VIOLATED and GOAL_TOLERANCE_VIOLATED: Which joint
        //    violated which tolerance, and by how much.
        public string error_string;

        public FollowJointTrajectoryResult()
        {
            this.error_code = 0;
            this.error_string = "";
        }

        public FollowJointTrajectoryResult(int error_code, string error_string)
        {
            this.error_code = error_code;
            this.error_string = error_string;
        }

        public static FollowJointTrajectoryResult Deserialize(MessageDeserializer deserializer) => new FollowJointTrajectoryResult(deserializer);

        private FollowJointTrajectoryResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.error_code);
            deserializer.Read(out this.error_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
            serializer.Write(this.error_string);
        }

        public override string ToString()
        {
            return "FollowJointTrajectoryResult: " +
            "\nerror_code: " + error_code.ToString() +
            "\nerror_string: " + error_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
