//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class JointTrajectoryFeedback : Message
    {
        public const string k_RosMessageName = "control_msgs/JointTrajectory";
        public override string RosMessageName => k_RosMessageName;


        public JointTrajectoryFeedback()
        {
        }
        public static JointTrajectoryFeedback Deserialize(MessageDeserializer deserializer) => new JointTrajectoryFeedback(deserializer);

        private JointTrajectoryFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "JointTrajectoryFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
