//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SingleJointPositionGoal : Message
    {
        public const string k_RosMessageName = "control_msgs/SingleJointPosition";
        public override string RosMessageName => k_RosMessageName;

        public double position;
        public BuiltinInterfaces.DurationMsg min_duration;
        public double max_velocity;

        public SingleJointPositionGoal()
        {
            this.position = 0.0;
            this.min_duration = new BuiltinInterfaces.DurationMsg();
            this.max_velocity = 0.0;
        }

        public SingleJointPositionGoal(double position, BuiltinInterfaces.DurationMsg min_duration, double max_velocity)
        {
            this.position = position;
            this.min_duration = min_duration;
            this.max_velocity = max_velocity;
        }

        public static SingleJointPositionGoal Deserialize(MessageDeserializer deserializer) => new SingleJointPositionGoal(deserializer);

        private SingleJointPositionGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            this.min_duration = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.max_velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.min_duration);
            serializer.Write(this.max_velocity);
        }

        public override string ToString()
        {
            return "SingleJointPositionGoal: " +
            "\nposition: " + position.ToString() +
            "\nmin_duration: " + min_duration.ToString() +
            "\nmax_velocity: " + max_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
