//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    [Serializable]
    public class UInt32Msg : Message
    {
        public const string k_RosMessageName = "std_msgs/UInt32";
        public override string RosMessageName => k_RosMessageName;

        public uint data;

        public UInt32Msg()
        {
            this.data = 0;
        }

        public UInt32Msg(uint data)
        {
            this.data = data;
        }

        public static UInt32Msg Deserialize(MessageDeserializer deserializer) => new UInt32Msg(deserializer);

        private UInt32Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "UInt32Msg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
