//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class ContactsStateMsg : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/ContactsState";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        //  stamp
        public ContactStateMsg[] states;
        //  array of geom pairs in contact

        public ContactsStateMsg()
        {
            this.header = new HeaderMsg();
            this.states = new ContactStateMsg[0];
        }

        public ContactsStateMsg(HeaderMsg header, ContactStateMsg[] states)
        {
            this.header = header;
            this.states = states;
        }

        public static ContactsStateMsg Deserialize(MessageDeserializer deserializer) => new ContactsStateMsg(deserializer);

        private ContactsStateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.states, ContactStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "ContactsStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
