//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class ModelStatesMsg : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/ModelStates";
        public override string RosMessageName => k_RosMessageName;

        //  broadcast all model states in world frame
        public string[] name;
        //  model names
        public Geometry.PoseMsg[] pose;
        //  desired pose in world frame
        public Geometry.TwistMsg[] twist;
        //  desired twist in world frame

        public ModelStatesMsg()
        {
            this.name = new string[0];
            this.pose = new Geometry.PoseMsg[0];
            this.twist = new Geometry.TwistMsg[0];
        }

        public ModelStatesMsg(string[] name, Geometry.PoseMsg[] pose, Geometry.TwistMsg[] twist)
        {
            this.name = name;
            this.pose = pose;
            this.twist = twist;
        }

        public static ModelStatesMsg Deserialize(MessageDeserializer deserializer) => new ModelStatesMsg(deserializer);

        private ModelStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.pose, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.twist, Geometry.TwistMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.pose);
            serializer.Write(this.pose);
            serializer.WriteLength(this.twist);
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "ModelStatesMsg: " +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\npose: " + System.String.Join(", ", pose.ToList()) +
            "\ntwist: " + System.String.Join(", ", twist.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
