//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class ModelStateMsg : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/ModelState";
        public override string RosMessageName => k_RosMessageName;

        //  Set Gazebo Model pose and twist
        public string model_name;
        //  model to set state (pose and twist)
        public Geometry.PoseMsg pose;
        //  desired pose in reference frame
        public Geometry.TwistMsg twist;
        //  desired twist in reference frame
        public string reference_frame;
        //  set pose/twist relative to the frame of this entity (Body/Model)
        //  leave empty or "world" or "map" defaults to world-frame

        public ModelStateMsg()
        {
            this.model_name = "";
            this.pose = new Geometry.PoseMsg();
            this.twist = new Geometry.TwistMsg();
            this.reference_frame = "";
        }

        public ModelStateMsg(string model_name, Geometry.PoseMsg pose, Geometry.TwistMsg twist, string reference_frame)
        {
            this.model_name = model_name;
            this.pose = pose;
            this.twist = twist;
            this.reference_frame = reference_frame;
        }

        public static ModelStateMsg Deserialize(MessageDeserializer deserializer) => new ModelStateMsg(deserializer);

        private ModelStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
            deserializer.Read(out this.reference_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
            serializer.Write(this.pose);
            serializer.Write(this.twist);
            serializer.Write(this.reference_frame);
        }

        public override string ToString()
        {
            return "ModelStateMsg: " +
            "\nmodel_name: " + model_name.ToString() +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString() +
            "\nreference_frame: " + reference_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
