//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class ODEPhysicsMsg : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/ODEPhysics";
        public override string RosMessageName => k_RosMessageName;

        public bool auto_disable_bodies;
        //  enable auto disabling of bodies, default false
        public uint sor_pgs_precon_iters;
        //  preconditioning inner iterations when uisng projected Gauss Seidel
        public uint sor_pgs_iters;
        //  inner iterations when uisng projected Gauss Seidel
        public double sor_pgs_w;
        //  relaxation parameter when using projected Gauss Seidel, 1 = no relaxation
        public double sor_pgs_rms_error_tol;
        //  rms error tolerance before stopping inner iterations
        public double contact_surface_layer;
        //  contact "dead-band" width
        public double contact_max_correcting_vel;
        //  contact maximum correction velocity
        public double cfm;
        //  global constraint force mixing
        public double erp;
        //  global error reduction parameter
        public uint max_contacts;
        //  maximum contact joints between two geoms

        public ODEPhysicsMsg()
        {
            this.auto_disable_bodies = false;
            this.sor_pgs_precon_iters = 0;
            this.sor_pgs_iters = 0;
            this.sor_pgs_w = 0.0;
            this.sor_pgs_rms_error_tol = 0.0;
            this.contact_surface_layer = 0.0;
            this.contact_max_correcting_vel = 0.0;
            this.cfm = 0.0;
            this.erp = 0.0;
            this.max_contacts = 0;
        }

        public ODEPhysicsMsg(bool auto_disable_bodies, uint sor_pgs_precon_iters, uint sor_pgs_iters, double sor_pgs_w, double sor_pgs_rms_error_tol, double contact_surface_layer, double contact_max_correcting_vel, double cfm, double erp, uint max_contacts)
        {
            this.auto_disable_bodies = auto_disable_bodies;
            this.sor_pgs_precon_iters = sor_pgs_precon_iters;
            this.sor_pgs_iters = sor_pgs_iters;
            this.sor_pgs_w = sor_pgs_w;
            this.sor_pgs_rms_error_tol = sor_pgs_rms_error_tol;
            this.contact_surface_layer = contact_surface_layer;
            this.contact_max_correcting_vel = contact_max_correcting_vel;
            this.cfm = cfm;
            this.erp = erp;
            this.max_contacts = max_contacts;
        }

        public static ODEPhysicsMsg Deserialize(MessageDeserializer deserializer) => new ODEPhysicsMsg(deserializer);

        private ODEPhysicsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.auto_disable_bodies);
            deserializer.Read(out this.sor_pgs_precon_iters);
            deserializer.Read(out this.sor_pgs_iters);
            deserializer.Read(out this.sor_pgs_w);
            deserializer.Read(out this.sor_pgs_rms_error_tol);
            deserializer.Read(out this.contact_surface_layer);
            deserializer.Read(out this.contact_max_correcting_vel);
            deserializer.Read(out this.cfm);
            deserializer.Read(out this.erp);
            deserializer.Read(out this.max_contacts);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.auto_disable_bodies);
            serializer.Write(this.sor_pgs_precon_iters);
            serializer.Write(this.sor_pgs_iters);
            serializer.Write(this.sor_pgs_w);
            serializer.Write(this.sor_pgs_rms_error_tol);
            serializer.Write(this.contact_surface_layer);
            serializer.Write(this.contact_max_correcting_vel);
            serializer.Write(this.cfm);
            serializer.Write(this.erp);
            serializer.Write(this.max_contacts);
        }

        public override string ToString()
        {
            return "ODEPhysicsMsg: " +
            "\nauto_disable_bodies: " + auto_disable_bodies.ToString() +
            "\nsor_pgs_precon_iters: " + sor_pgs_precon_iters.ToString() +
            "\nsor_pgs_iters: " + sor_pgs_iters.ToString() +
            "\nsor_pgs_w: " + sor_pgs_w.ToString() +
            "\nsor_pgs_rms_error_tol: " + sor_pgs_rms_error_tol.ToString() +
            "\ncontact_surface_layer: " + contact_surface_layer.ToString() +
            "\ncontact_max_correcting_vel: " + contact_max_correcting_vel.ToString() +
            "\ncfm: " + cfm.ToString() +
            "\nerp: " + erp.ToString() +
            "\nmax_contacts: " + max_contacts.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
