//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class SensorPerformanceMetricMsg : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/SensorPerformanceMetric";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public double sim_update_rate;
        public double real_update_rate;
        public double fps;

        public SensorPerformanceMetricMsg()
        {
            this.name = "";
            this.sim_update_rate = 0.0;
            this.real_update_rate = 0.0;
            this.fps = 0.0;
        }

        public SensorPerformanceMetricMsg(string name, double sim_update_rate, double real_update_rate, double fps)
        {
            this.name = name;
            this.sim_update_rate = sim_update_rate;
            this.real_update_rate = real_update_rate;
            this.fps = fps;
        }

        public static SensorPerformanceMetricMsg Deserialize(MessageDeserializer deserializer) => new SensorPerformanceMetricMsg(deserializer);

        private SensorPerformanceMetricMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.sim_update_rate);
            deserializer.Read(out this.real_update_rate);
            deserializer.Read(out this.fps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.sim_update_rate);
            serializer.Write(this.real_update_rate);
            serializer.Write(this.fps);
        }

        public override string ToString()
        {
            return "SensorPerformanceMetricMsg: " +
            "\nname: " + name.ToString() +
            "\nsim_update_rate: " + sim_update_rate.ToString() +
            "\nreal_update_rate: " + real_update_rate.ToString() +
            "\nfps: " + fps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
