//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class BodyRequestRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/BodyRequest";
        public override string RosMessageName => k_RosMessageName;

        public string body_name;
        //  name of the body requested. body names are prefixed by model name, e.g. pr2::base_link

        public BodyRequestRequest()
        {
            this.body_name = "";
        }

        public BodyRequestRequest(string body_name)
        {
            this.body_name = body_name;
        }

        public static BodyRequestRequest Deserialize(MessageDeserializer deserializer) => new BodyRequestRequest(deserializer);

        private BodyRequestRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.body_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.body_name);
        }

        public override string ToString()
        {
            return "BodyRequestRequest: " +
            "\nbody_name: " + body_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
