//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetLinkStateRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetLinkState";
        public override string RosMessageName => k_RosMessageName;

        public string link_name;
        //  name of link
        //  link names are prefixed by model name, e.g. pr2::base_link
        public string reference_frame;
        //  reference frame of returned information, must be a valid link
        //  if empty, use inertial (gazebo world) frame
        //  reference_frame names are prefixed by model name, e.g. pr2::base_link

        public GetLinkStateRequest()
        {
            this.link_name = "";
            this.reference_frame = "";
        }

        public GetLinkStateRequest(string link_name, string reference_frame)
        {
            this.link_name = link_name;
            this.reference_frame = reference_frame;
        }

        public static GetLinkStateRequest Deserialize(MessageDeserializer deserializer) => new GetLinkStateRequest(deserializer);

        private GetLinkStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.link_name);
            deserializer.Read(out this.reference_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.link_name);
            serializer.Write(this.reference_frame);
        }

        public override string ToString()
        {
            return "GetLinkStateRequest: " +
            "\nlink_name: " + link_name.ToString() +
            "\nreference_frame: " + reference_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
