//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetLinkStateResponse : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetLinkState";
        public override string RosMessageName => k_RosMessageName;

        public LinkStateMsg link_state;
        public bool success;
        //  return true if get info is successful
        public string status_message;
        //  comments if available

        public GetLinkStateResponse()
        {
            this.link_state = new LinkStateMsg();
            this.success = false;
            this.status_message = "";
        }

        public GetLinkStateResponse(LinkStateMsg link_state, bool success, string status_message)
        {
            this.link_state = link_state;
            this.success = success;
            this.status_message = status_message;
        }

        public static GetLinkStateResponse Deserialize(MessageDeserializer deserializer) => new GetLinkStateResponse(deserializer);

        private GetLinkStateResponse(MessageDeserializer deserializer)
        {
            this.link_state = LinkStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.success);
            deserializer.Read(out this.status_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.link_state);
            serializer.Write(this.success);
            serializer.Write(this.status_message);
        }

        public override string ToString()
        {
            return "GetLinkStateResponse: " +
            "\nlink_state: " + link_state.ToString() +
            "\nsuccess: " + success.ToString() +
            "\nstatus_message: " + status_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
