//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetLightPropertiesRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetLightProperties";
        public override string RosMessageName => k_RosMessageName;

        public string light_name;
        //  name of Gazebo Light

        public GetLightPropertiesRequest()
        {
            this.light_name = "";
        }

        public GetLightPropertiesRequest(string light_name)
        {
            this.light_name = light_name;
        }

        public static GetLightPropertiesRequest Deserialize(MessageDeserializer deserializer) => new GetLightPropertiesRequest(deserializer);

        private GetLightPropertiesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.light_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.light_name);
        }

        public override string ToString()
        {
            return "GetLightPropertiesRequest: " +
            "\nlight_name: " + light_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
