//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetModelPropertiesRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetModelProperties";
        public override string RosMessageName => k_RosMessageName;

        public string model_name;
        //  name of Gazebo Model

        public GetModelPropertiesRequest()
        {
            this.model_name = "";
        }

        public GetModelPropertiesRequest(string model_name)
        {
            this.model_name = model_name;
        }

        public static GetModelPropertiesRequest Deserialize(MessageDeserializer deserializer) => new GetModelPropertiesRequest(deserializer);

        private GetModelPropertiesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
        }

        public override string ToString()
        {
            return "GetModelPropertiesRequest: " +
            "\nmodel_name: " + model_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
