//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetModelStateRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetModelState";
        public override string RosMessageName => k_RosMessageName;

        public string model_name;
        //  name of Gazebo Model
        public string relative_entity_name;
        //  return pose and twist relative to this entity
        //  an entity can be a model, body, or geom
        //  be sure to use gazebo scoped naming notation (e.g. [model_name::body_name])
        //  leave empty or "world" will use inertial world frame

        public GetModelStateRequest()
        {
            this.model_name = "";
            this.relative_entity_name = "";
        }

        public GetModelStateRequest(string model_name, string relative_entity_name)
        {
            this.model_name = model_name;
            this.relative_entity_name = relative_entity_name;
        }

        public static GetModelStateRequest Deserialize(MessageDeserializer deserializer) => new GetModelStateRequest(deserializer);

        private GetModelStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
            deserializer.Read(out this.relative_entity_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
            serializer.Write(this.relative_entity_name);
        }

        public override string ToString()
        {
            return "GetModelStateRequest: " +
            "\nmodel_name: " + model_name.ToString() +
            "\nrelative_entity_name: " + relative_entity_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
