//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class GetWorldPropertiesRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/GetWorldProperties";
        public override string RosMessageName => k_RosMessageName;


        public GetWorldPropertiesRequest()
        {
        }
        public static GetWorldPropertiesRequest Deserialize(MessageDeserializer deserializer) => new GetWorldPropertiesRequest(deserializer);

        private GetWorldPropertiesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetWorldPropertiesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
