//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class JointRequestResponse : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/JointRequest";
        public override string RosMessageName => k_RosMessageName;


        public JointRequestResponse()
        {
        }
        public static JointRequestResponse Deserialize(MessageDeserializer deserializer) => new JointRequestResponse(deserializer);

        private JointRequestResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "JointRequestResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
