//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class SetJointPropertiesRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/SetJointProperties";
        public override string RosMessageName => k_RosMessageName;

        public string joint_name;
        //  name of joint
        public ODEJointPropertiesMsg ode_joint_config;
        //  access to ODE joint dynamics properties

        public SetJointPropertiesRequest()
        {
            this.joint_name = "";
            this.ode_joint_config = new ODEJointPropertiesMsg();
        }

        public SetJointPropertiesRequest(string joint_name, ODEJointPropertiesMsg ode_joint_config)
        {
            this.joint_name = joint_name;
            this.ode_joint_config = ode_joint_config;
        }

        public static SetJointPropertiesRequest Deserialize(MessageDeserializer deserializer) => new SetJointPropertiesRequest(deserializer);

        private SetJointPropertiesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_name);
            this.ode_joint_config = ODEJointPropertiesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_name);
            serializer.Write(this.ode_joint_config);
        }

        public override string ToString()
        {
            return "SetJointPropertiesRequest: " +
            "\njoint_name: " + joint_name.ToString() +
            "\node_joint_config: " + ode_joint_config.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
