//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class SetJointTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/SetJointTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public string model_name;
        public Trajectory.JointTrajectoryMsg joint_trajectory;
        public Geometry.PoseMsg model_pose;
        public bool set_model_pose;
        public bool disable_physics_updates;
        //  defaults to false

        public SetJointTrajectoryRequest()
        {
            this.model_name = "";
            this.joint_trajectory = new Trajectory.JointTrajectoryMsg();
            this.model_pose = new Geometry.PoseMsg();
            this.set_model_pose = false;
            this.disable_physics_updates = false;
        }

        public SetJointTrajectoryRequest(string model_name, Trajectory.JointTrajectoryMsg joint_trajectory, Geometry.PoseMsg model_pose, bool set_model_pose, bool disable_physics_updates)
        {
            this.model_name = model_name;
            this.joint_trajectory = joint_trajectory;
            this.model_pose = model_pose;
            this.set_model_pose = set_model_pose;
            this.disable_physics_updates = disable_physics_updates;
        }

        public static SetJointTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new SetJointTrajectoryRequest(deserializer);

        private SetJointTrajectoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
            this.joint_trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
            this.model_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.set_model_pose);
            deserializer.Read(out this.disable_physics_updates);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
            serializer.Write(this.joint_trajectory);
            serializer.Write(this.model_pose);
            serializer.Write(this.set_model_pose);
            serializer.Write(this.disable_physics_updates);
        }

        public override string ToString()
        {
            return "SetJointTrajectoryRequest: " +
            "\nmodel_name: " + model_name.ToString() +
            "\njoint_trajectory: " + joint_trajectory.ToString() +
            "\nmodel_pose: " + model_pose.ToString() +
            "\nset_model_pose: " + set_model_pose.ToString() +
            "\ndisable_physics_updates: " + disable_physics_updates.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
