//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class SetModelStateRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/SetModelState";
        public override string RosMessageName => k_RosMessageName;

        public ModelStateMsg model_state;

        public SetModelStateRequest()
        {
            this.model_state = new ModelStateMsg();
        }

        public SetModelStateRequest(ModelStateMsg model_state)
        {
            this.model_state = model_state;
        }

        public static SetModelStateRequest Deserialize(MessageDeserializer deserializer) => new SetModelStateRequest(deserializer);

        private SetModelStateRequest(MessageDeserializer deserializer)
        {
            this.model_state = ModelStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_state);
        }

        public override string ToString()
        {
            return "SetModelStateRequest: " +
            "\nmodel_state: " + model_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
