//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gazebo
{
    [Serializable]
    public class SetModelConfigurationRequest : Message
    {
        public const string k_RosMessageName = "gazebo_msgs/SetModelConfiguration";
        public override string RosMessageName => k_RosMessageName;

        //  Set joint positions for a model
        public string model_name;
        //  model to set state
        public string urdf_param_name;
        //  UNUSED
        public string[] joint_names;
        //  list of joints to set positions.  if joint is not listed here, preserve current position.
        public double[] joint_positions;
        //  set to this position.

        public SetModelConfigurationRequest()
        {
            this.model_name = "";
            this.urdf_param_name = "";
            this.joint_names = new string[0];
            this.joint_positions = new double[0];
        }

        public SetModelConfigurationRequest(string model_name, string urdf_param_name, string[] joint_names, double[] joint_positions)
        {
            this.model_name = model_name;
            this.urdf_param_name = urdf_param_name;
            this.joint_names = joint_names;
            this.joint_positions = joint_positions;
        }

        public static SetModelConfigurationRequest Deserialize(MessageDeserializer deserializer) => new SetModelConfigurationRequest(deserializer);

        private SetModelConfigurationRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
            deserializer.Read(out this.urdf_param_name);
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.joint_positions, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
            serializer.Write(this.urdf_param_name);
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.WriteLength(this.joint_positions);
            serializer.Write(this.joint_positions);
        }

        public override string ToString()
        {
            return "SetModelConfigurationRequest: " +
            "\nmodel_name: " + model_name.ToString() +
            "\nurdf_param_name: " + urdf_param_name.ToString() +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\njoint_positions: " + System.String.Join(", ", joint_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
