//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class DynamicJointStateMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/DynamicJointState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  List of resource names, e.g. ["arm_joint_1", "arm_joint_2", "gripper_joint"]
        public string[] joint_names;
        //  Key-value pairs representing interfaces and their corresponding values for each joint listed in `joint_names`
        public InterfaceValueMsg[] interface_values;

        public DynamicJointStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.joint_names = new string[0];
            this.interface_values = new InterfaceValueMsg[0];
        }

        public DynamicJointStateMsg(Std.HeaderMsg header, string[] joint_names, InterfaceValueMsg[] interface_values)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.interface_values = interface_values;
        }

        public static DynamicJointStateMsg Deserialize(MessageDeserializer deserializer) => new DynamicJointStateMsg(deserializer);

        private DynamicJointStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.interface_values, InterfaceValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.WriteLength(this.interface_values);
            serializer.Write(this.interface_values);
        }

        public override string ToString()
        {
            return "DynamicJointStateMsg: " +
            "\nheader: " + header.ToString() +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\ninterface_values: " + System.String.Join(", ", interface_values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
