//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class GripperCommandMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/GripperCommand";
        public override string RosMessageName => k_RosMessageName;

        public double position;
        public double max_effort;

        public GripperCommandMsg()
        {
            this.position = 0.0;
            this.max_effort = 0.0;
        }

        public GripperCommandMsg(double position, double max_effort)
        {
            this.position = position;
            this.max_effort = max_effort;
        }

        public static GripperCommandMsg Deserialize(MessageDeserializer deserializer) => new GripperCommandMsg(deserializer);

        private GripperCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.max_effort);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.max_effort);
        }

        public override string ToString()
        {
            return "GripperCommandMsg: " +
            "\nposition: " + position.ToString() +
            "\nmax_effort: " + max_effort.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
