//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Com3
{
    [Serializable]
    public class FluidPressureArrayMsg : Message
    {
        public const string k_RosMessageName = "com3_msgs/FluidPressureArray";
        public override string RosMessageName => k_RosMessageName;

        //  THis message publishes values for multiple FuluidPressure at once.
        public Sensor.FluidPressureMsg[] array;

        public FluidPressureArrayMsg()
        {
            this.array = new Sensor.FluidPressureMsg[0];
        }

        public FluidPressureArrayMsg(Sensor.FluidPressureMsg[] array)
        {
            this.array = array;
        }

        public static FluidPressureArrayMsg Deserialize(MessageDeserializer deserializer) => new FluidPressureArrayMsg(deserializer);

        private FluidPressureArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.array, Sensor.FluidPressureMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.array);
            serializer.Write(this.array);
        }

        public override string ToString()
        {
            return "FluidPressureArrayMsg: " +
            "\narray: " + System.String.Join(", ", array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
