//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Com3
{
    [Serializable]
    public class JointCmdMsg : Message
    {
        public const string k_RosMessageName = "com3_msgs/JointCmd";
        public override string RosMessageName => k_RosMessageName;

        //  joint name of control target.
        public string[] joint_name;
        //  controlled variable for each joint name
        public double[] position;
        public double[] velocity;
        public double[] effort;

        public JointCmdMsg()
        {
            this.joint_name = new string[0];
            this.position = new double[0];
            this.velocity = new double[0];
            this.effort = new double[0];
        }

        public JointCmdMsg(string[] joint_name, double[] position, double[] velocity, double[] effort)
        {
            this.joint_name = joint_name;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
        }

        public static JointCmdMsg Deserialize(MessageDeserializer deserializer) => new JointCmdMsg(deserializer);

        private JointCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_name, deserializer.ReadLength());
            deserializer.Read(out this.position, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.velocity, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.effort, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_name);
            serializer.Write(this.joint_name);
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.velocity);
            serializer.Write(this.velocity);
            serializer.WriteLength(this.effort);
            serializer.Write(this.effort);
        }

        public override string ToString()
        {
            return "JointCmdMsg: " +
            "\njoint_name: " + System.String.Join(", ", joint_name.ToList()) +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\nvelocity: " + System.String.Join(", ", velocity.ToList()) +
            "\neffort: " + System.String.Join(", ", effort.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
